#!/usr/bin/env python

import fileinput
from rss_feed import rss_feed
import subprocess
import fcntl

ZERO_COMMIT = "0000000000000000000000000000000000000000"
BASE_PATH = "/home/git/rss/bioconductor.org/assets/developers/rss-feeds/"
WEBSITE_DIR = "/home/git/rss/bioconductor.org/"


def git_pull(cwd):
    """Git svn fetch branch."""
    cmd = ['git', '-C', cwd ,'pull']
    # subprocess.check_call(cmd)
    print(cmd)
    return


def git_add(path, cwd, force=False):
    """Add files to git."""
    cmd = ['git', '-C', cwd, 'add', path]
    if force:
        cmd = ['git', '-C', cwd ,'add', '-f', path]
    # subprocess.check_call(cmd)
    print(cmd)
    return


def git_commit(message, cwd):
    """Commit files to git server."""
    cmd = ['git', '-C', cwd, 'commit', '-a', '-m', message]
    #subprocess.check_call(cmd)
    print(cmd)
    return


def git_push(cwd, remote="origin", branch="master"):
    """Git svn fetch branch."""
    cmd = ['git', '-C', cwd,  'push', remote, branch]
    #subprocess.check_call(cmd)
    print(cmd)
    return


if __name__ == "__main__":
    # Path to feed.xml
    fpath = BASE_PATH + "gitlog.xml"
    fpath_release = BASE_PATH + "gitlog.release.xml"
    length = 200
    # Run function for RSS feed
    fh = open(fpath, 'r+')
    fh2 = open(fpath_release, 'r+')

    # Obtain a lock
    fcntl.lockf(fh, fcntl.LOCK_EX)
    fcntl.lockf(fh2, fcntl.LOCK_EX)

    # git pull from website
    git_pull(WEBSITE_DIR)

    for line in fileinput.input():
        std_input = line.split(" ")
        oldrev, newrev, refname = [item.strip() for item in std_input]
        # Check for zero commit, check branch deletions
        # also, avoid new package additions
        if (oldrev == ZERO_COMMIT or newrev == ZERO_COMMIT):
            continue
        # Split feed into correct files
        if ("RELEASE" in refname):
            # RSS-feed post-receive hook
            rss_feed(oldrev, newrev, refname, fh2, length)
        else:
            rss_feed(oldrev, newrev, refname, fh, length)

    # git add and commit to gitolite
    git_commit("RSS feed update", WEBSITE_DIR)
    # git push to gitolite: bioconductor.org
    git_push(WEBSITE_DIR)
    # Release the lock
    fcntl.lockf(fh, fcntl.LOCK_UN)
    fcntl.lockf(fh2, fcntl.LOCK_UN)
    fh.close()
    fh2.close()
