#!/usr/bin/env python

"""
Enable post receive hook for Bioconductor packages for RSS feeds.
"""

import fileinput
import subprocess
import fcntl
import sys
from rss_feed import rss_feed
from rss_feed import indent_xml
from rss_feed import write_and_limit_feed

# Global variables used by post-recieve hook
ZERO_COMMIT = "0000000000000000000000000000000000000000"
BASE_PATH = "/home/git/rss/"


def apply_hooks():
    # Path to feed.xml
    fpath = BASE_PATH + "gitlog.xml"
    fpath_release = BASE_PATH + "gitlog.release.xml"
    length = 499

    # Run function for RSS feed
    feed = open(fpath, "r+")
    feed_release = open(fpath_release, 'r+')

    # Obtain a lock
    fcntl.lockf(feed, fcntl.LOCK_EX)

    for line in fileinput.input():
        std_input = line.split(" ")
        oldrev, newrev, refname = [item.strip() for item in std_input]
        # Check for zero commit, check branch deletions
        # also, avoid new package additions
        if ZERO_COMMIT in (oldrev, newrev):
            continue
        # Split feed into correct files
        try:
            if "RELEASE" in refname:
                # RSS-feed post-receive hook
                entry = rss_feed(oldrev, newrev, refname, length)
                write_and_limit_feed(entry, length, feed_release)
            else:
                entry = rss_feed(oldrev, newrev, refname, length)
                write_and_limit_feed(entry, length, feed)
        except Exception as err:
            print("Note: failed to update RSS feed; git repository updated successfully.")

    # Url for sending the RSS feed
    url = 'biocadmin@staging.bioconductor.org' + \
        ':/home/biocadmin/bioc-test-web/bioconductor.org' + \
        '/assets/developers/rss-feeds/.'
    # Run subprocess command
    cmd = ['scp', 'gitlog.xml', 'gitlog.release.xml', url]
    subprocess.check_call(cmd, cwd=BASE_PATH)

    # Release the lock
    fcntl.lockf(feed, fcntl.LOCK_UN)
    feed.close()
    feed_release.close()
    return

if __name__ == "__main__":
    apply_hooks()
