#!/usr/bin/env python

import fileinput
from rss_feed import rss_feed


ZERO_COMMIT = "0000000000000000000000000000000000000000"


if __name__ == "__main__":
    # Path to feed.xml
    fpath = "/home/git/rss/gitlog.xml"
    fpath_release = "/home/git/rss/gitlog.release.xml"
    # FIXME: Change length to 200 once testing is over
    length = 20
    # Run function for RSS feed
    for line in fileinput.input():
        std_input = line.split(" ")
        oldrev, newrev, refname = [item.strip() for item in std_input]
        # Check for zero commit, check branch deletions
        # also, avoid new package additions
        if (oldrev == ZERO_COMMIT or newrev == ZERO_COMMIT):
            continue
        # Split feed into correct files
        if ("RELEASE" in refname):
            # RSS-feed post-receive hook
            rss_feed(oldrev, newrev, refname, fpath_release, length)
        else:
            rss_feed(oldrev, newrev, refname, fpath, length)
